<?php

namespace Database\Seeders;

use App\Models\AppMenu;
use App\Models\AppModule;
use Illuminate\Database\Seeder;

class AppNavigationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $modules = [
            [
                'id' => 'dashboard',
                'name' => 'Dashboard',
                'icon' => 'LayoutDashboard',
                'description' => 'Ringkasan operasional dan statistik terpadu',
                'sort_order' => 1,
                'platform' => 'both',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'dash-super-admin',
                        'name' => 'Dashboard Super Admin',
                        'path' => '/dashboard',
                        'icon' => 'ShieldCheck',
                        'required_permissions' => ['dashboard.super-admin.view'],
                        'sort_order' => 1,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-yayasan',
                        'name' => 'Dashboard Yayasan',
                        'path' => '/dashboard/yayasan',
                        'icon' => 'Building2',
                        'required_permissions' => ['foundation.dashboard.view'],
                        'sort_order' => 2,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-profil-yayasan',
                        'name' => 'Profil Yayasan',
                        'path' => '/dashboard/yayasan/profil',
                        'icon' => 'Building2',
                        'required_permissions' => ['foundation.profile.view', 'foundation.dashboard.view'],
                        'sort_order' => 3,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-kepsek',
                        'name' => 'Dashboard Kepala Sekolah',
                        'path' => '/dashboard/kepala-sekolah',
                        'icon' => 'LayoutDashboard',
                        'required_permissions' => ['dashboard.kepala-sekolah.view'],
                        'sort_order' => 4,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-divisi',
                        'name' => 'Dashboard Divisi Pendidikan',
                        'path' => '/dashboard/divisi-pendidikan',
                        'icon' => 'Layers',
                        'required_permissions' => ['dashboard.divisi-pendidikan.view'],
                        'sort_order' => 5,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-waka-kurikulum',
                        'name' => 'Dashboard Waka Kurikulum',
                        'path' => '/dashboard/waka-kurikulum',
                        'icon' => 'Compass',
                        'required_permissions' => ['dashboard.waka-kurikulum.view'],
                        'sort_order' => 6,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-tu',
                        'name' => 'Dashboard Tata Usaha',
                        'path' => '/dashboard/tata-usaha',
                        'icon' => 'Briefcase',
                        'required_permissions' => ['dashboard.tata-usaha.view'],
                        'sort_order' => 7,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-tahfizh',
                        'name' => 'Dashboard Guru Tahfizh',
                        'path' => '/dashboard/guru-tahfizh',
                        'icon' => 'BookHeart',
                        'required_permissions' => ['dashboard.guru-tahfizh.view'],
                        'sort_order' => 8,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'portal-guru-workspace',
                        'name' => 'Workspace Guru',
                        'path' => '/portal-guru/workspace',
                        'icon' => 'GraduationCap',
                        'required_permissions' => ['teacher.workspace.view', 'teacher.dashboard.view'],
                        'sort_order' => 9,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'portal-musyrif-workspace',
                        'name' => 'Workspace Musyrif',
                        'path' => '/musyrif/workspace',
                        'icon' => 'Home',
                        'required_permissions' => ['musyrif.workspace.view'],
                        'sort_order' => 10,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'dash-monitoring',
                        'name' => 'Monitoring Operasional',
                        'path' => '/dashboard/monitoring-divisi',
                        'icon' => 'CalendarCheck',
                        'required_permissions' => ['dashboard.pemantauan.lihat', 'divisi.monitoring'],
                        'sort_order' => 11,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'dash-pemantauan',
                        'name' => 'Pemantauan Divisi & Guru',
                        'path' => '/dashboard/pemantauan',
                        'icon' => 'Activity',
                        'required_permissions' => ['teacher_monitoring.view', 'monitoring.view'],
                        'sort_order' => 12,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'portal-sivitas',
                        'name' => 'Portal Siswa & Wali Murid',
                        'path' => '/portal',
                        'icon' => 'Users',
                        'required_permissions' => ['parent.portal.view', 'student.portal.view'],
                        'sort_order' => 13,
                        'platform' => 'both',
                    ],
                ],
            ],
            [
                'id' => 'master-data',
                'name' => 'Master Data',
                'icon' => 'Database',
                'description' => 'Manajemen data pokok sekolah dan sivitas akademika',
                'sort_order' => 2,
                'platform' => 'web',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'master-unit',
                        'name' => 'Unit Pendidikan',
                        'path' => '/dashboard/master/unit-pendidikan',
                        'icon' => 'Building2',
                        'required_permissions' => ['unit.view_all'],
                        'sort_order' => 1,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-pegawai',
                        'name' => 'Pegawai & Guru',
                        'path' => '/dashboard/master/pegawai',
                        'icon' => 'Users',
                        'required_permissions' => ['employee.view_all', 'foundation.employee.view', 'dashboard.pemantauan.lihat'],
                        'sort_order' => 2,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-siswa',
                        'name' => 'Buku Induk Siswa',
                        'path' => '/dashboard/master/siswa',
                        'icon' => 'Users',
                        'required_permissions' => ['student.view', 'student.view_all', 'kesiswaan.data_lengkap_siswa'],
                        'sort_order' => 3,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-kelas',
                        'name' => 'Kelas & Rombel',
                        'path' => '/dashboard/master/kelas',
                        'icon' => 'Layers',
                        'required_permissions' => ['kesiswaan.kelas_rombel'],
                        'sort_order' => 4,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-tahun-ajaran',
                        'name' => 'Tahun Ajaran',
                        'path' => '/dashboard/master/tahun-ajaran',
                        'icon' => 'Calendar',
                        'required_permissions' => ['sistem.master_data'],
                        'sort_order' => 5,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-mata-pelajaran',
                        'name' => 'Mata Pelajaran',
                        'path' => '/dashboard/master/mata-pelajaran',
                        'icon' => 'BookOpen',
                        'required_permissions' => ['sistem.master_data'],
                        'sort_order' => 6,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-users',
                        'name' => 'Manajemen Akun',
                        'path' => '/dashboard/master-hak-akses',
                        'icon' => 'ShieldCheck',
                        'required_permissions' => ['user.manage', 'sistem.hak_akses', 'sistem.master_data'],
                        'sort_order' => 7,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-jenis-unit',
                        'name' => 'Jenis Unit Pendidikan',
                        'path' => '/dashboard/master-jenis-unit',
                        'icon' => 'Layers',
                        'required_permissions' => ['unit.view_all', 'sistem.master_data'],
                        'sort_order' => 8,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'master-jabatan',
                        'name' => 'Master Jabatan',
                        'path' => '/dashboard/master-jabatan',
                        'icon' => 'Briefcase',
                        'required_permissions' => ['position.view', 'sistem.master_data', 'employee.view'],
                        'sort_order' => 9,
                        'platform' => 'web',
                    ],
                ],
            ],
            [
                'id' => 'akademik',
                'name' => 'Akademik & KBM',
                'icon' => 'BookOpen',
                'description' => 'Kurikulum, jadwal pelajaran, dan kalender pendidikan',
                'sort_order' => 3,
                'platform' => 'both',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'akademik-kurikulum',
                        'name' => 'Master Kurikulum',
                        'path' => '/dashboard/master/kurikulum',
                        'icon' => 'BookMarked',
                        'required_permissions' => ['academic.manage', 'pembelajaran.kurikulum.view'],
                        'sort_order' => 1,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'akademik-jadwal',
                        'name' => 'Jadwal Pelajaran',
                        'path' => '/dashboard/akademik/jadwal',
                        'icon' => 'CalendarDays',
                        'required_permissions' => ['academic.schedule.view', 'pembelajaran.jadwal_pelajaran', 'teacher.schedule.view', 'academic.manage', 'sistem.master_data'],
                        'sort_order' => 2,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'akademik-kalender',
                        'name' => 'Kalender Akademik',
                        'path' => '/dashboard/akademik/kalender',
                        'icon' => 'Calendar',
                        'required_permissions' => ['academic.manage', 'sistem.master_data', 'academic.schedule.view'],
                        'sort_order' => 3,
                        'platform' => 'both',
                    ],
                ],
            ],
            [
                'id' => 'lms',
                'name' => 'LMS & E-Learning',
                'icon' => 'Sparkles',
                'description' => 'Materi, bank soal, CBT ujian, dan penilaian',
                'sort_order' => 4,
                'platform' => 'both',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'lms-modul-ajar',
                        'name' => 'Modul Ajar',
                        'path' => '/dashboard/lms/modul-ajar',
                        'icon' => 'BookOpen',
                        'required_permissions' => ['teacher.material.view', 'academic.manage', 'lms.view'],
                        'sort_order' => 1,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'lms-materi',
                        'name' => 'Materi Belajar',
                        'path' => '/dashboard/lms/materi',
                        'icon' => 'BookMarked',
                        'required_permissions' => ['teacher.material.view', 'student.material.view', 'lms.view'],
                        'sort_order' => 2,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'lms-diskusi',
                        'name' => 'Forum Diskusi',
                        'path' => '/dashboard/lms/diskusi',
                        'icon' => 'Users',
                        'required_permissions' => ['lms.view', 'lms.manage'],
                        'sort_order' => 3,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'lms-kisi-kisi',
                        'name' => 'Kisi-kisi Ujian',
                        'path' => '/dashboard/lms/kisi-kisi',
                        'icon' => 'Target',
                        'required_permissions' => ['pembelajaran.kisi_kisi_ujian', 'lms.view'],
                        'sort_order' => 4,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'lms-bank-soal',
                        'name' => 'Bank Soal',
                        'path' => '/dashboard/lms/bank-soal',
                        'icon' => 'Database',
                        'required_permissions' => ['pembelajaran.bank_soal', 'lms.view'],
                        'sort_order' => 5,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'lms-ujian',
                        'name' => 'CBT Ujian Online',
                        'path' => '/dashboard/lms/ujian',
                        'icon' => 'FileText',
                        'required_permissions' => ['pembelajaran.kisi_kisi_ujian', 'lms.view', 'lms.manage'],
                        'sort_order' => 6,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'lms-penugasan',
                        'name' => 'Tugas Siswa',
                        'path' => '/dashboard/lms/penugasan',
                        'icon' => 'FileText',
                        'required_permissions' => ['kesiswaan.penugasan_siswa', 'lms.view'],
                        'sort_order' => 7,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'lms-penilaian',
                        'name' => 'Penilaian & Rapor',
                        'path' => '/dashboard/lms/penilaian',
                        'icon' => 'CreditCard',
                        'required_permissions' => ['academic.rapor.view', 'academic.rapor.create', 'teacher.grade.view', 'pembelajaran.penilaian_siswa', 'academic.view'],
                        'sort_order' => 8,
                        'platform' => 'web',
                    ],
                ],
            ],
            [
                'id' => 'presensi',
                'name' => 'Presensi & Kehadiran',
                'icon' => 'CalendarCheck',
                'description' => 'Presensi KBM, gerbang RFID, dan monitoring kehadiran',
                'sort_order' => 5,
                'platform' => 'both',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'presensi-kbm',
                        'name' => 'Presensi KBM',
                        'path' => '/absensi/kbm',
                        'icon' => 'CalendarCheck',
                        'required_permissions' => ['lesson_attendance.view', 'lesson_attendance.view_own', 'attendance.view'],
                        'sort_order' => 1,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'presensi-gerbang',
                        'name' => 'Presensi Gerbang',
                        'path' => '/dashboard/rekap-absensi-gerbang',
                        'icon' => 'CalendarDays',
                        'required_permissions' => ['kehadiran.siswa.monitoring'],
                        'sort_order' => 2,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'presensi-device',
                        'name' => 'Scanner Gerbang',
                        'path' => '/dashboard/absensi-gerbang',
                        'icon' => 'ShieldCheck',
                        'required_permissions' => ['attendance_device.manage', 'gate_attendance.scan', 'gate_attendance.view'],
                        'sort_order' => 3,
                        'platform' => 'both',
                    ],
                ],
            ],
            [
                'id' => 'mutabaah',
                'name' => 'Tahfizh & Mutabaah',
                'icon' => 'BookHeart',
                'description' => 'Catatan ibadah yaumiyah, hafalan Qur’an, dan adab santri',
                'sort_order' => 6,
                'platform' => 'both',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'mutabaah-harian',
                        'name' => 'Mutabaah Yaumiyah',
                        'path' => '/mutabaah',
                        'icon' => 'BookHeart',
                        'required_permissions' => ['mutabaah.daily.view', 'mutabaah.view'],
                        'sort_order' => 1,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'mutabaah-tahfizh',
                        'name' => 'Setoran Tahfizh',
                        'path' => '/dashboard/tahfizh',
                        'icon' => 'BookOpen',
                        'required_permissions' => ['tahfizh.monitoring_target', 'tahfizh.input_setoran_harian'],
                        'sort_order' => 2,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'mutabaah-agenda',
                        'name' => 'Agenda & Template',
                        'path' => '/mutabaah/agenda',
                        'icon' => 'Layers',
                        'required_permissions' => ['mutabaah.agenda.manage', 'mutabaah.agenda.view', 'mutabaah.create'],
                        'sort_order' => 3,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'mutabaah-shalat',
                        'name' => 'Penilaian Shalat & Ibadah',
                        'path' => '/dashboard/absensi-ibadah-siswa',
                        'icon' => 'CalendarCheck',
                        'required_permissions' => ['worship_attendance.view', 'worship_assessment.setting.manage'],
                        'sort_order' => 4,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'tahfizh-quran',
                        'name' => 'Al-Qur\'an (114 Surah)',
                        'path' => '/dashboard/master-quran-surah',
                        'icon' => 'BookOpen',
                        'required_permissions' => ['equran.view', 'tahfizh.view', 'teacher.tahfizh.view', 'student.portal.view'],
                        'sort_order' => 5,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'tahfizh-doa',
                        'name' => 'Doa & Dzikir',
                        'path' => '/dashboard/master-doa',
                        'icon' => 'Heart',
                        'required_permissions' => ['equran.view', 'tahfizh.view', 'teacher.tahfizh.view', 'student.portal.view'],
                        'sort_order' => 6,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'tahfizh-jadwal-sholat',
                        'name' => 'Jadwal Sholat',
                        'path' => '/dashboard/master-jadwal-sholat',
                        'icon' => 'Clock',
                        'required_permissions' => ['prayer.schedule.view', 'equran.view', 'tahfizh.view'],
                        'sort_order' => 7,
                        'platform' => 'both',
                    ],
                    [
                        'id' => 'tahfizh-poin-doa',
                        'name' => 'Poin Penilaian Doa',
                        'path' => '/dashboard/poin-penilaian-doa',
                        'icon' => 'CheckSquare',
                        'required_permissions' => ['prayer.assessment.view', 'tahfizh.view'],
                        'sort_order' => 8,
                        'platform' => 'web',
                    ],
                ],
            ],
            [
                'id' => 'laporan',
                'name' => 'Laporan & Eksekutif',
                'icon' => 'FileText',
                'description' => 'Laporan presensi, siswa, prestasi, dan rekap yayasan',
                'sort_order' => 7,
                'platform' => 'web',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'lap-absensi',
                        'name' => 'Laporan Absensi',
                        'path' => '/dashboard/laporan-absensi',
                        'icon' => 'CalendarCheck',
                        'required_permissions' => ['report.attendance.view'],
                        'sort_order' => 1,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'lap-siswa',
                        'name' => 'Laporan Siswa',
                        'path' => '/dashboard/laporan-siswa',
                        'icon' => 'Users',
                        'required_permissions' => ['report.student.view', 'student.view_all'],
                        'sort_order' => 2,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'lap-prestasi',
                        'name' => 'Laporan Prestasi',
                        'path' => '/dashboard/laporan-prestasi',
                        'icon' => 'Sparkles',
                        'required_permissions' => ['foundation.report.view', 'kesiswaan.rekap_prestasi', 'kesiswaan.prestasi_rekapitulasi'],
                        'sort_order' => 3,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'lap-lintas-unit',
                        'name' => 'Laporan Lintas Unit',
                        'path' => '/dashboard/yayasan/laporan/lintas-unit',
                        'icon' => 'Building2',
                        'required_permissions' => ['foundation.report.view', 'report.cross_unit.view'],
                        'sort_order' => 4,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'lap-alumni',
                        'name' => 'Kelola Alumni & Mutasi',
                        'path' => '/dashboard/kelola-alumni',
                        'icon' => 'Users',
                        'required_permissions' => ['foundation.report.view', 'alumni.view', 'kesiswaan.kelulusan_per_tahun', 'kesiswaan.alumni_tujuan_lanjut'],
                        'sort_order' => 5,
                        'platform' => 'web',
                    ],
                ],
            ],
            [
                'id' => 'pengaturan',
                'name' => 'Pengaturan',
                'icon' => 'Settings',
                'description' => 'Konfigurasi aplikasi, hak akses, dan profil lembaga',
                'sort_order' => 8,
                'platform' => 'web',
                'is_active' => true,
                'menus' => [
                    [
                        'id' => 'set-sekolah',
                        'name' => 'Pengaturan Sekolah',
                        'path' => '/dashboard/pengaturan',
                        'icon' => 'Settings',
                        'required_permissions' => ['sistem.pengaturan'],
                        'sort_order' => 1,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'set-mobile',
                        'name' => 'Konfigurasi Mobile & PWA',
                        'path' => '/dashboard/koneksi-api-mobile',
                        'icon' => 'CreditCard',
                        'required_permissions' => ['sistem.pengaturan'],
                        'sort_order' => 2,
                        'platform' => 'web',
                    ],
                    [
                        'id' => 'pengaturan-info-sekolah',
                        'name' => 'Informasi Sekolah',
                        'path' => '/dashboard/informasi-sekolah',
                        'icon' => 'Info',
                        'required_permissions' => ['school.info.view', 'setting.view', 'sistem.master_data'],
                        'sort_order' => 3,
                        'platform' => 'web',
                    ],
                ],
            ],
        ];

        foreach ($modules as $modData) {
            $menus = $modData['menus'] ?? [];
            unset($modData['menus']);

            $module = AppModule::query()->updateOrCreate(
                ['id' => $modData['id']],
                $modData
            );

            foreach ($menus as $menuData) {
                $menuData['module_id'] = $module->id;
                $menuData['is_active'] = true;

                AppMenu::query()->updateOrCreate(
                    ['id' => $menuData['id']],
                    $menuData
                );
            }
        }
    }
}
