<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            'Super Admin',
            'Yayasan',
            'Kepala Sekolah',
            'Wakil Kepala Sekolah',
            'Divisi Pendidikan',
            'Tata Usaha',
            'Guru',
            'Wali Kelas',
            'Orang Tua',
            'Siswa',
        ];

        $permissions = [
            // Dashboard & Pemantauan
            'dashboard.view',
            'dashboard.pemantauan.lihat',
            'dashboard.pemantauan.kelola',
            'divisi.monitoring',
            'divisi.laporan_bulanan',

            // Kehadiran & Absensi Siswa
            'kehadiran.siswa.monitoring',
            'kehadiran.siswa.absensi_digital',
            'kehadiran.siswa.rekap_keterlambatan',
            'kehadiran.siswa.rekap_ketidakhadiran',
            'kehadiran.siswa.barcode_kartu',
            'kehadiran.siswa.izin_sakit',

            // Presensi Pembelajaran berbasis jadwal (permission baru, permission lama dipertahankan)
            'lesson_attendance.view',
            'lesson_attendance.view_own',
            'lesson_attendance.create',
            'lesson_attendance.update',
            'lesson_attendance.finalize',
            'lesson_attendance.unlock',
            'lesson_attendance.cancel',
            'lesson_attendance.correct',
            'lesson_attendance.export',
            'homeroom_attendance.dashboard',
            'homeroom_attendance.view',
            'homeroom_attendance.follow_up',
            'homeroom_attendance.verify_permission',
            'homeroom_attendance.export',
            'student_attendance.view_own',
            'student_attendance.permission.create',
            'student_attendance.permission.update',
            'student_attendance.permission.cancel',
            'lesson_attendance.manual',
            'lesson_attendance.qr_scan',
            'lesson_attendance.barcode_scan',
            'lesson_attendance.face_scan',
            'lesson_attendance.fingerprint_scan',
            'lesson_attendance.session.start',
            'lesson_attendance.session.close',
            'lesson_attendance.scan_logs.view',
            'attendance_device.view',
            'attendance_device.manage',
            'attendance_device.receive_event',

            // Tahfizh & Mutabaah
            'tahfizh.monitoring_target',
            'tahfizh.input_setoran_harian',
            'tahfizh.hitung_baris',
            'tahfizh.rekap_harian',
            'tahfizh.rekap_mingguan',
            'tahfizh.rekap_bulanan',
            'tahfizh.rekap_tahunan',
            'tahfizh.mutabaah_yaumiyah',
            'tahfizh.laporan_target',
            'tahfizh.perhitungan_tercapai',
            'tahfizh.hafalan_terbanyak',
            'tahfizh.total_hafalan',

            // Kesiswaan & Kelulusan
            'kesiswaan.rekap_prestasi',
            'kesiswaan.kelulusan_per_unit',
            'kesiswaan.kelulusan_per_tahun',
            'kesiswaan.alumni_tujuan_lanjut',
            'kesiswaan.data_lengkap_siswa',
            'kesiswaan.kelas_rombel',
            'kesiswaan.laporan_masuk_keluar',
            'kesiswaan.penugasan_siswa',
            'kesiswaan.catatan_siswa',

            // Pembelajaran & Kurikulum
            'pembelajaran.kurikulum.view',
            'pembelajaran.kurikulum.create',
            'pembelajaran.kurikulum.edit',
            'pembelajaran.kurikulum.delete',
            'pembelajaran.kurikulum.restore',
            'pembelajaran.kurikulum.export',
            'pembelajaran.kurikulum.import',
            'pembelajaran.materi',
            'pembelajaran.kisi_kisi_ujian',
            'pembelajaran.bank_soal',
            'pembelajaran.jadwal_pelajaran',
            'pembelajaran.kalender_pendidikan',

            // Informasi Sekolah & Data Pribadi
            'sekolah.data_pribadi_siswa',
            'sekolah.informasi_sekolah',

            // Administrasi sistem (khusus Super Admin)
            'sistem.hak_akses',
            'sistem.pengaturan',
            'sistem.master_data',
        ];

        foreach ($permissions as $permissionName) {
            Permission::query()->firstOrCreate([
                'name' => $permissionName,
                'guard_name' => 'web',
            ]);
        }

        $rolePermissionMap = [
            'Super Admin' => $permissions,
            'Kepala Sekolah' => [
                'dashboard.view',
                'dashboard.pemantauan.lihat',
                'dashboard.pemantauan.kelola',
                'divisi.monitoring',
                'divisi.laporan_bulanan',
                'kehadiran.siswa.monitoring',
                'kehadiran.siswa.absensi_digital',
                'kehadiran.siswa.rekap_keterlambatan',
                'kehadiran.siswa.rekap_ketidakhadiran',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'tahfizh.perhitungan_tercapai',
                'tahfizh.hafalan_terbanyak',
                'tahfizh.total_hafalan',
                'kesiswaan.rekap_prestasi',
                'kesiswaan.kelulusan_per_unit',
                'kesiswaan.kelulusan_per_tahun',
                'kesiswaan.alumni_tujuan_lanjut',
                'kesiswaan.data_lengkap_siswa',
                'kesiswaan.kelas_rombel',
                'kesiswaan.laporan_masuk_keluar',
                'kesiswaan.penugasan_siswa',
                'kesiswaan.catatan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'pembelajaran.jadwal_pelajaran',
                'pembelajaran.kalender_pendidikan',
            ],
            'Yayasan' => [
                'dashboard.view',
                'dashboard.pemantauan.lihat',
                'divisi.monitoring',
                'divisi.laporan_bulanan',
                'kesiswaan.rekap_prestasi',
                'kesiswaan.kelulusan_per_tahun',
            ],
            'Divisi Pendidikan' => [
                'dashboard.view',
                'dashboard.pemantauan.lihat',
                'dashboard.pemantauan.kelola',
                'divisi.monitoring',
                'divisi.laporan_bulanan',
                'kesiswaan.rekap_prestasi',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'tahfizh.perhitungan_tercapai',
                'tahfizh.hafalan_terbanyak',
                'tahfizh.total_hafalan',
                'kesiswaan.kelulusan_per_unit',
                'kesiswaan.kelulusan_per_tahun',
                'kesiswaan.alumni_tujuan_lanjut',
                'kesiswaan.data_lengkap_siswa',
                'kesiswaan.kelas_rombel',
                'kesiswaan.laporan_masuk_keluar',
                'pembelajaran.jadwal_pelajaran',
                'pembelajaran.kalender_pendidikan',
            ],
            'Tata Usaha' => [
                'dashboard.view',
                'kehadiran.siswa.absensi_digital',
                'kehadiran.siswa.rekap_keterlambatan',
                'kehadiran.siswa.rekap_ketidakhadiran',
                'kesiswaan.kelulusan_per_tahun',
                'kesiswaan.alumni_tujuan_lanjut',
                'kesiswaan.penugasan_siswa',
                'kesiswaan.catatan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'pembelajaran.jadwal_pelajaran',
                'pembelajaran.kalender_pendidikan',
            ],
            'Guru' => [
                'dashboard.view',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'tahfizh.perhitungan_tercapai',
                'tahfizh.hafalan_terbanyak',
                'tahfizh.total_hafalan',
                'lesson_attendance.view_own',
                'lesson_attendance.create',
                'lesson_attendance.update',
                'lesson_attendance.finalize',
                'lesson_attendance.cancel',
                'lesson_attendance.correct',
                'lesson_attendance.export',
                'lesson_attendance.manual',
                'lesson_attendance.qr_scan',
                'lesson_attendance.barcode_scan',
                'lesson_attendance.face_scan',
                'lesson_attendance.fingerprint_scan',
                'lesson_attendance.session.start',
                'lesson_attendance.session.close',
                'lesson_attendance.scan_logs.view',
            ],
            'Wali Kelas' => [
                'dashboard.view',
                'kehadiran.siswa.monitoring',
                'kehadiran.siswa.absensi_digital',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'kesiswaan.penugasan_siswa',
                'kesiswaan.catatan_siswa',
                'pembelajaran.materi',
                'pembelajaran.jadwal_pelajaran',
                'homeroom_attendance.dashboard',
                'homeroom_attendance.view',
                'homeroom_attendance.follow_up',
                'homeroom_attendance.verify_permission',
                'homeroom_attendance.export',
                'lesson_attendance.correct',
            ],
            'Orang Tua' => [
                'dashboard.view',
                'kehadiran.siswa.barcode_kartu',
                'kehadiran.siswa.izin_sakit',
                'tahfizh.laporan_target',
                'sekolah.data_pribadi_siswa',
                'sekolah.informasi_sekolah',
                'kesiswaan.penugasan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
            ],
            'Siswa' => [
                'dashboard.view',
                'kehadiran.siswa.barcode_kartu',
                'kehadiran.siswa.izin_sakit',
                'tahfizh.laporan_target',
                'sekolah.data_pribadi_siswa',
                'sekolah.informasi_sekolah',
                'kesiswaan.penugasan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'student_attendance.view_own',
                'student_attendance.permission.create',
                'student_attendance.permission.update',
                'student_attendance.permission.cancel',
            ],
        ];

        foreach ($roles as $roleName) {
            $role = Role::query()->firstOrCreate([
                'name' => $roleName,
                'guard_name' => 'web',
            ]);

            if (isset($rolePermissionMap[$roleName])) {
                $role->syncPermissions($rolePermissionMap[$roleName]);
            }
        }
    }
}
